// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnoowjiafklnxbnddifs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhub293amlhZmtsbnhibmRkaWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzE0OTksImV4cCI6MjA2Mzg0NzQ5OX0.RebpQySTayBxbiXVENFWFCsKKsSJRDLIobiikuDw9x4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);